In [256]:
import numpy as np 
import pandas as pd

Nettoyage du dataframe Clubs

In [257]:
clubs = pd.read_csv("data/clubs_fr.csv")
clubs = clubs.drop(columns=["foreigners_number", "foreigners_percentage"])

matchs_2013_2024 = pd.read_csv("data/matchs_2013_2024.csv", index_col=0)
matchs_2013_2024 = matchs_2013_2024.drop(columns=["home_club_formation", "away_club_formation"])

print("Clubs :")
display(clubs.head())
print()

print("Matchs from 2013 to 2024 :")
display(matchs_2013_2024.head())

Clubs :

,club_id,club_code,name,domestic_competition_id,squad_size,average_age,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name
0,10004,paris-fc,Paris Football Club,FR1,31,28.5,9,Stade Jean Bouin,19904,€-72.30m,NaN
1,1041,olympique-lyon,Olympique Lyonnais,FR1,28,25.5,11,Groupama Stadium,59186,+€62.11m,NaN
2,1082,losc-lille,Lille Olympique Sporting Club,FR1,27,26.5,11,Decathlon Arena-Stade Pierre-Mauroy,50186,+€61.60m,NaN
3,1095,es-troyes-ac,ESTAC Troyes,FR1,29,23.1,5,Stade de l'Aube,21877,+-0,NaN
4,1147,ac-ajaccio,AC Ajaccio,FR1,24,27.5,6,Stade François-Coty,10446,+-0,NaN

Matchs from 2013 to 2024 :

,game_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,away_club_position,home_club_manager_name,away_club_manager_name,stadium,attendance,referee,home_club_name,away_club_name,aggregate,competition_type,results
523,2223841,2012,6. Matchday,2012-09-22,3911,1423,2,1,8.0,9.0,Landry Chauvin,Daniel Sanchez,Stade Francis-Le Blé,10627.0,Sébastien Moreira,Stade brestois 29,Valenciennes FC,2:1,domestic_league,1
524,2223842,2012,7. Matchday,2012-09-29,1147,3911,1,0,9.0,10.0,Alex Dupont,Landry Chauvin,Stade François-Coty,6029.0,Olivier Thual,AC Ajaccio,Stade brestois 29,1:0,domestic_league,1
525,2223843,2012,6. Matchday,2012-09-22,1421,1159,2,0,5.0,19.0,Hubert Fournier,Jean Fernandez,Stade Auguste-Delaune,13413.0,Jean-Charles Cailleux,Stade Reims,AS Nancy-Lorraine,2:0,domestic_league,1
526,2223844,2012,6. Matchday,2012-09-21,969,618,1,1,16.0,10.0,René Girard,Christophe Galtier,Stade de la Mosson,16666.0,Lionel Jaffredo,Montpellier HSC,AS Saint-Étienne,1:1,domestic_league,0
527,2223845,2012,6. Matchday,2012-09-23,1082,1041,1,1,12.0,2.0,Rudi Garcia,Rémi Garde,Decathlon Arena-Stade Pierre-Mauroy,43475.0,Clément Turpin,Lille Olympique Sporting Club,Olympique Lyonnais,1:1,domestic_league,0

In [258]:
clubs = clubs.drop(columns=["club_code", "net_transfer_record", "stadium_name", "domestic_competition_id", "name", "coach_name"])
print("Clubs clean :")
display(clubs.head())

print()
print("Matchs 2013 2024 clean :")
matchs_2013_2024 = matchs_2013_2024.drop(columns=["home_club_goals", "away_club_goals", "aggregate", "competition_type"])
matchs_2013_2024 = matchs_2013_2024.dropna(subset="results")
display(matchs_2013_2024.head())

Clubs clean :

   club_id  squad_size  average_age  national_team_players  stadium_seats
0    10004          31         28.5                      9          19904
1     1041          28         25.5                     11          59186
2     1082          27         26.5                     11          50186
3     1095          29         23.1                      5          21877
4     1147          24         27.5                      6          10446

Matchs 2013 2024 clean :

,game_id,season,round,date,home_club_id,away_club_id,home_club_position,away_club_position,home_club_manager_name,away_club_manager_name,stadium,attendance,referee,home_club_name,away_club_name,results
523,2223841,2012,6. Matchday,2012-09-22,3911,1423,8.0,9.0,Landry Chauvin,Daniel Sanchez,Stade Francis-Le Blé,10627.0,Sébastien Moreira,Stade brestois 29,Valenciennes FC,1
524,2223842,2012,7. Matchday,2012-09-29,1147,3911,9.0,10.0,Alex Dupont,Landry Chauvin,Stade François-Coty,6029.0,Olivier Thual,AC Ajaccio,Stade brestois 29,1
525,2223843,2012,6. Matchday,2012-09-22,1421,1159,5.0,19.0,Hubert Fournier,Jean Fernandez,Stade Auguste-Delaune,13413.0,Jean-Charles Cailleux,Stade Reims,AS Nancy-Lorraine,1
526,2223844,2012,6. Matchday,2012-09-21,969,618,16.0,10.0,René Girard,Christophe Galtier,Stade de la Mosson,16666.0,Lionel Jaffredo,Montpellier HSC,AS Saint-Étienne,0
527,2223845,2012,6. Matchday,2012-09-23,1082,1041,12.0,2.0,Rudi Garcia,Rémi Garde,Decathlon Arena-Stade Pierre-Mauroy,43475.0,Clément Turpin,Lille Olympique Sporting Club,Olympique Lyonnais,0

In [259]:
matchs_2013_2024 = pd.merge(matchs_2013_2024, clubs, left_on="home_club_id", right_on="club_id")
matchs_2013_2024 = matchs_2013_2024.drop(columns=["club_id"])
matchs_2013_2024 = matchs_2013_2024.rename(columns={"squad_size": "home_club_squad_size", "average_age": "home_club_average_age", "national_team_players": "home_club_national_team_players"})
print(matchs_2013_2024.columns)
matchs_2013_2024.head()

Index(['game_id', 'season', 'round', 'date', 'home_club_id', 'away_club_id',
       'home_club_position', 'away_club_position', 'home_club_manager_name',
       'away_club_manager_name', 'stadium', 'attendance', 'referee',
       'home_club_name', 'away_club_name', 'results', 'home_club_squad_size',
       'home_club_average_age', 'home_club_national_team_players',
       'stadium_seats'],
      dtype='str')

,game_id,season,round,date,home_club_id,away_club_id,home_club_position,away_club_position,home_club_manager_name,away_club_manager_name,stadium,attendance,referee,home_club_name,away_club_name,results,home_club_squad_size,home_club_average_age,home_club_national_team_players,stadium_seats
0,2223841,2012,6. Matchday,2012-09-22,3911,1423,8.0,9.0,Landry Chauvin,Daniel Sanchez,Stade Francis-Le Blé,10627.0,Sébastien Moreira,Stade brestois 29,Valenciennes FC,1,23,25.3,6,15220
1,2223842,2012,7. Matchday,2012-09-29,1147,3911,9.0,10.0,Alex Dupont,Landry Chauvin,Stade François-Coty,6029.0,Olivier Thual,AC Ajaccio,Stade brestois 29,1,24,27.5,6,10446
2,2223843,2012,6. Matchday,2012-09-22,1421,1159,5.0,19.0,Hubert Fournier,Jean Fernandez,Stade Auguste-Delaune,13413.0,Jean-Charles Cailleux,Stade Reims,AS Nancy-Lorraine,1,24,23.9,7,20519
3,2223844,2012,6. Matchday,2012-09-21,969,618,16.0,10.0,René Girard,Christophe Galtier,Stade de la Mosson,16666.0,Lionel Jaffredo,Montpellier HSC,AS Saint-Étienne,0,24,24.2,3,22000
4,2223845,2012,6. Matchday,2012-09-23,1082,1041,12.0,2.0,Rudi Garcia,Rémi Garde,Decathlon Arena-Stade Pierre-Mauroy,43475.0,Clément Turpin,Lille Olympique Sporting Club,Olympique Lyonnais,0,27,26.5,11,50186

Dataframe Game Events Before 2025

In [260]:
game_events_before2025 = pd.read_csv("data/game_events_before2025.csv")
game_events_before2025.head()

,Unnamed: 0,game_event_id,date,game_id,minute,type,club_id,club_name,player_id,description,player_in_id,player_assist_id
0,6816,5d2b67957aaae6cf2a41e70cb5d4024f,2012-09-22,2223841,73,Substitutions,3911,Stade Brestois 29,5399,", Not reported",37516.0,NaN
1,6817,cd511880b945623db06ace57349e45b2,2012-09-22,2223841,76,Goals,3911,Stade Brestois 29,24459,", Penalty, 2. Goal of the Season Assist: , Fou...",NaN,24459.0
2,6818,8ca118538b45a24643ab1c9f76e50f6d,2012-09-22,2223841,56,Substitutions,3911,Stade Brestois 29,25113,", Not reported",22053.0,NaN
3,6819,aca68dc250aa9a3758fb2243ee679d9d,2012-09-22,2223841,88,Cards,1423,Valenciennes FC,27490,1. Yellow card,NaN,NaN
4,6820,a133e4d7cdccb930f2dc7b4935754a30,2012-09-22,2223841,4,Cards,1423,Valenciennes FC,43960,1. Yellow card,NaN,NaN

In [261]:
game_lineups = pd.read_csv("data/game_lineups.csv")
# game_lineups.head()

/var/folders/kp/j1c9d35x2ql0126h0tyh5_t80000gn/T/ipykernel_85425/942601742.py:1: DtypeWarning: Columns (0: number) have mixed types. Specify dtype option on import or set low_memory=False.
  game_lineups = pd.read_csv("data/game_lineups.csv")

In [262]:
game_lineups = game_lineups.drop(columns=["number"])
game_lineups.head()

,Unnamed: 0,game_lineups_id,date,game_id,player_id,club_id,player_name,type,position,team_captain
0,34475,be6532aeff4c40b06e6e0da142da7dd8,2013-08-24,2330825,4811,969,Hilton,starting_lineup,Centre-Back,1
1,34476,4b10516c5bf9b2dfac0435c7c2bbf872,2013-08-24,2330825,5303,969,Souleymane Camara,starting_lineup,Left Winger,0
2,34477,46552e9ff9777efa2e2d0df3a8147d87,2013-08-24,2330825,5614,750,Cédric Kanté,starting_lineup,Centre-Back,1
3,34478,9c10d07e15ca9a537576aa4c04511562,2013-08-24,2330825,5686,969,Laurent Pionnier,starting_lineup,Goalkeeper,0
4,34479,d6592bfd4c2c2f06a388086f8b0b714e,2013-08-24,2330825,17693,750,Sébastien Roudet,starting_lineup,Left Winger,0

In [263]:
match_2025 = pd.read_csv("data/match_2025.csv")
match_2025.head()

,game_id,date,home_club_id,away_club_id,home_club_manager_name,away_club_manager_name,stadium,attendance,referee,home_club_name,away_club_name,competition_type
0,4635006,2025-08-15,273,244,Habib Beye,Roberto De Zerbi,Roazhon Park,28360.0,Jérémie Pignard,Stade Rennais Football Club,Olympique de Marseille,domestic_league
1,4635007,2025-08-16,826,1041,Pierre Sage,Paulo Fonseca,Stade Bollaert-Delelis,38137.0,Romain Lissorgue,Racing Club de Lens,Olympique Lyonnais,domestic_league
2,4635008,2025-08-16,417,415,Franck Haise,Carles Martínez,Allianz Riviera,23212.0,Thomas Léonard,Olympique Gymnaste Club Nice Côte d'Azur,Toulouse Football Club,domestic_league
3,4635009,2025-08-17,290,1158,Christophe Pélissier,Olivier Pantaloni,Stade de l'Abbé-Deschamps,16090.0,Abdelatif Kherradji,Association de la Jeunesse auxerroise,Football Club Lorient-Bretagne Sud,domestic_league
4,4635010,2025-08-17,3911,1082,Éric Roy,Bruno Génésio,Stade Francis-Le Blé,14840.0,Clément Turpin,Stade brestois 29,Lille Olympique Sporting Club,domestic_league

Merge tableau player

In [264]:
player_appearance = pd.read_csv("data/player_appearance.csv")
player_appearance.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2229837_108830,2229837,108830,415,3205,2012-08-10,Aymen Abdennour,FR1,1,0,0,0,90
1,2229837_113707,2229837,113707,969,1082,2012-08-10,Rémy Cabella,FR1,1,0,0,0,42
2,2229837_126767,2229837,126767,415,3205,2012-08-10,Ali Ahamada,FR1,0,0,0,0,90
3,2229837_126796,2229837,126796,415,60949,2012-08-10,Adrien Regattin,FR1,0,1,0,0,11
4,2229837_127032,2229837,127032,415,703,2012-08-10,Serge Aurier,FR1,0,1,0,1,84

In [265]:
player_valuation_before_season = pd.read_csv("data/player_valuation_before_season.csv")
player_valuation_before_season.head()

,player_id,date,market_value_in_eur,current_club_name,current_club_id,player_club_domestic_competition_id
0,773,2004-10-04,3500000,Hamburger SV,14171,FR1
1,1327,2004-10-04,4000000,RC Lens,1159,FR1
2,1423,2004-10-04,1000000,FC Copenhagen,855,FR1
3,1572,2004-10-04,1000000,1.FC Nuremberg,162,FR1
4,1613,2004-10-04,200000,UD Las Palmas,855,FR1